source_repo: "git@github.com:audioidiom/applied_ml_ops.git"
rev: 'master'
data_path: 'data'
model_path: '${data_path}/main_model/ridge.skops'

preprocessing:
  imputer_path: '${data_path}/preprocessing_models/median_imputer.skops'
  normalizer_path: '${data_path}/preprocessing_models/normalizer_for_nums.skops'
  encoder_path: "${data_path}/preprocessing_models/encoder_for_categorical.skops"

train:
  mode: 'train'
  df_path: '${data_path}/datasets/cars_train.csv'
  model:
    _target_: sklearn.linear_model.Ridge
    alpha: 506

infer:
  mode: 'infer'
  df_path: '${data_path}/datasets/cars_test.csv'
  pred_csv_path: '${data_path}/predictions/y_pred.csv'

mlflow_global:
  uri: "http://128.0.1.1:8080"
  experiment_name: "Ridge best params"
